# the default 80 character limit is sometimes unproductive;
# changing character limit to 120 characters per line
LineLength:
  Max: 120

# the default 10 lines limit is unrealistic;
# changing method loc to 15; #WeLoveLongMethods
MethodLength:
  Max: 15

# ignoring vendored gems; we don't care about other people code
AllCops:
  Exclude:
    - 'vendor/*'

# adding frozen_string_literal: false to every ruby file
# is annoying; will be re-visiting when Ruby 3.0 releases
Style/FrozenStringLiteralComment:
  Enabled: false

# going old-skool with hash rockets, son
Style/HashSyntax:
  Enabled: false

# nothing is better than a well indented + padded hashes;
# they're more readable + #MakeHashesGreatAgain
Layout/IndentHash:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
